### ISSUE TITLE
The offset in deformable conv

### ISSUE THREAD

**Issue by yangle15** [jwr1995/dc1d#1]
Great job!
I found that the deformconv1d in this repo is different from the original one. If I'm right, the deformable kernel will not change when facing different inputs. Since the offsets are set as the learnable parameters, which will be fixed after the training, all samples will use the same offset parameters to conduct the deformable 1d convolution. While the original deformable conv can change the form of the kernel based on the input samples.

Is that correct?

**Comment by jwr1995** [comment]
Either is possible. You can use a torch.nn.Parameter if you want fixed offsets or, for example, torch.nn.Conv1D to compute the offsets for each input frame. I included a class called PackedConv1D which already does this for variable offsets based on a depthwise separable convolutional structure using stacked 1D convolutions, see the offset subnetwork in Fig. 3 of my [paper](https://arxiv.org/abs/2210.15305)
