### ISSUE TITLE
Error in running the DeformConv1d

### ISSUE THREAD

**Issue by shayanjalilpour** [jwr1995/dc1d#2]
Hi,

I used the provided functions, and tried to run the sample code in the README.md.
But I got this error that the length of input and output are different.

    _**assert in_shape[-1] == output.shape[-1], f"input length {in_shape[-1]} and output length {output.shape[-1]} do not match."
AssertionError: input length 128 and output length 83 do not match.**_ 

Thanks,

**Comment by jwr1995** [comment]
I'll try take a look later. Would you be able to provide the full stack trace please?

**Comment by shayanjalilpour** [comment]
Here is the full stack trace:

Traceback (most recent call last):

  File "C:\Users\Shayan\AppData\Local\Temp/ipykernel_12540/4106152862.py", line 2, in <module>
    y = model(x, offsets)

  File "C:\Users\Shayan\anaconda3\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)

  File "D:\DL_EEG\data\DeepL_models\dc1d.py", line 240, in forward
    assert in_shape[-1] == output.shape[-1], f"input length {in_shape[-1]} and output length {output.shape[-1]} do not match."

AssertionError: input length 128 and output length 83 do not match.


Also, if you change  pack variable to False, in nn.py code, you will get the same error.
if __name__ == '__main__':
    # import time
    batch_size = 4
    in_channels = 512
    out_channels = 512
    kernel_size = 3
    stride = 1
    padding = "same"
    dilation = 2^7
    groups = 512
    bias = True
    length = 133
    packed = False

**Comment by jwr1995** [comment]
Make sure the offsets and input have the same length dimension, there is one buggy example in the current version if you wan python dc1d/nn.py ? Else I'm not sure where this issue is coming from at the moment

**Comment by jwr1995** [comment]
Okay figured out what you did here is the solution. I'm not sure why I used a separate output variable for output length of the offsets so I am a bit cautious about this solution. It should run but it may not 100% be giving you the desired padding. I will keep looking into this  
```
import time
import torch
from torch import nn

# Import layer
from dc1d.nn import DeformConv1d

# Hyperparameters
batch_size = 16
in_channels = 512
out_channels = 512
kernel_size = 16
stride = 1
padding = "valid"
dilation = 3
groups = 1
bias = True
length = 128

# Construct layer
model = DeformConv1d(
    in_channels = in_channels,
    out_channels = out_channels,
    kernel_size = kernel_size,
    stride = stride,
    padding = "same",
    dilation = dilation,
    groups = groups,
    bias = True,
)

# Generate input sequence
x = torch.rand(batch_size, in_channels, length,requires_grad=True)
print(x.shape)

# Generate offsets by first computing the desired output length
offsets = nn.Parameter(torch.ones(batch_size, 1, length, kernel_size, requires_grad=True))

# Process the input sequence and time it
start = time.time()
y = model(x, offsets)
end = time.time()

# Print output shape and time taken
print(y.shape)
print("Deformable runtime =",end-start)
```

**Comment by jwr1995** [comment]
The original issue was that the code wasn't passing "valid" padding to the DeformConv layer. I have updated the example code and added a playground with examples. I now consider this issue resolved and will close it.

**Comment by shayanjalilpour** [comment]
Thank you!
