### ISSUE TITLE
1D kernels using deform_conv2d

### ISSUE THREAD

**Issue by astrocyted** [jwr1995/dc1d#4]
Hi,

wouldn't it have been way easier to write the deform_conv1d as a small wrapper around deform_conv2d() in which you "unsqueeze()" the 1D input (and kernal dims) and pass zeros() for the offset channel corresponding to the unsqueezed (fabricated) dimension ?

**Comment by jwr1995** [comment]
Hi, yes this was what I originally did but for various reasons the pytorch `deformconv_2d` is not very good for interpretability and analysis or for example if you what control the minimum/maximum receptive field of the layer. This may not be important to many. Also if this is the kind of implementation you want I recommend another project called `tvdcn` at github.com/inspiros/tvdcn
