### ISSUE TITLE
How to learn offsets in 1D Convolution?

### ISSUE THREAD

**Issue by maryjis** [jwr1995/dc1d#5]
Hello! It is used Conv2d layer for learning offset  2D deformable convolution. In readme example you use such way to declare params:

 `offsets = nn.Parameter(torch.ones(batch_size, 1, output_length, kernel_size, requires_grad=True))
`
But how we can learn offsets for current input sequence x? Can you give some example?

**Comment by jwr1995** [comment]
Please see ``dc1d.nn.PackedDeformConv1D`` or Figure 3 in the paper cited in the README.md for examples using convolution

**Comment by maryjis** [comment]
Thank you!
